// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLZFS6-hbFz4OQBFkfWo5LQvi93YZuf9E',
    appId: '1:771687556873:web:83ad382146b18b273ad5d8',
    messagingSenderId: '771687556873',
    projectId: 'fir-notifications-b61ed',
    authDomain: 'fir-notifications-b61ed.firebaseapp.com',
    storageBucket: 'fir-notifications-b61ed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmSp4eJ47xTDU9taQ2sq2gvaOatOjEATE',
    appId: '1:771687556873:android:e8e26c00f5c49b323ad5d8',
    messagingSenderId: '771687556873',
    projectId: 'fir-notifications-b61ed',
    storageBucket: 'fir-notifications-b61ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkanqR7vMMYEHv2tl2SySkspTVkW1QCZc',
    appId: '1:771687556873:ios:5d564f27659aff483ad5d8',
    messagingSenderId: '771687556873',
    projectId: 'fir-notifications-b61ed',
    storageBucket: 'fir-notifications-b61ed.appspot.com',
    iosBundleId: 'com.example.firebaseNotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkanqR7vMMYEHv2tl2SySkspTVkW1QCZc',
    appId: '1:771687556873:ios:5d564f27659aff483ad5d8',
    messagingSenderId: '771687556873',
    projectId: 'fir-notifications-b61ed',
    storageBucket: 'fir-notifications-b61ed.appspot.com',
    iosBundleId: 'com.example.firebaseNotifications',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLZFS6-hbFz4OQBFkfWo5LQvi93YZuf9E',
    appId: '1:771687556873:web:e3ec6502c718f65f3ad5d8',
    messagingSenderId: '771687556873',
    projectId: 'fir-notifications-b61ed',
    authDomain: 'fir-notifications-b61ed.firebaseapp.com',
    storageBucket: 'fir-notifications-b61ed.appspot.com',
  );
}
